dist: bionic
language: cpp
os:
  - linux
compiler:
  - clang

addons:
  apt:
      packages: ['docker-ce', 'postgresql-server-dev-13']

before_script:
  - docker version

script:
  - make docker-image
